# Generated by Django 3.1.3 on 2020-12-01 06:13

import os
import json

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    City = apps.get_model('sky_status_app', 'City')

    fixture_file = os.path.abspath(os.path.join(
        os.path.dirname(__file__), '../fixtures/city_list.json'))
    with open(fixture_file) as f:
        cities = json.loads(f.read())
        for city in cities:
            City.objects.create(name=city['name'], city_id=city['id'])


def reverse_func(apps, schema_editor):
    City = apps.get_model('sky_status_app', 'City')
    City.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('sky_status_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
